# Generated by Django 2.2.16 on 2022-08-17 10:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='titles',
            options={'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AddField(
            model_name='genres',
            name='name',
            field=models.CharField(default='default genre name', max_length=256, verbose_name='Название жанра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genres',
            name='slug',
            field=models.SlugField(default='default genre slug', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='genre', to='reviews.Genres', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='titles',
            name='name',
            field=models.CharField(default='default title name', max_length=256, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titles',
            name='year',
            field=models.IntegerField(default=2020, validators=[django.core.validators.MaxValueValidator(2022)], verbose_name='Год'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='reviews.Categories', verbose_name='Категория'),
        ),
    ]
