# Generated by Django 2.2.16 on 2022-08-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220828_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.DateField(verbose_name='Год'),
        ),
    ]
