# Generated by Django 2.2.16 on 2022-08-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220828_0132'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['year', 'category'], name='reviews_tit_year_7fe8d0_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['year', 'name'], name='reviews_tit_year_128d06_idx'),
        ),
        migrations.AddIndex(
            model_name='title',
            index=models.Index(fields=['category', 'name'], name='reviews_tit_categor_98a89a_idx'),
        ),
    ]
