# Generated by Django 4.1.3 on 2022-11-15 16:09

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20220828_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.DateField(validators=[reviews.validators.year_validator], verbose_name='Год'),
        ),
    ]
